# Generated by Django 3.2.8 on 2023-03-16 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retailer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appname.retailer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.manufacturer'),
        ),
    ]
