# Generated by Django 3.2.8 on 2023-03-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_auto_20230316_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
