# Generated by Django 3.2.8 on 2023-03-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_block_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
